[theme]
# Cor primária para botões e elementos interativos
primaryColor="#00693C" # Um verde mais sóbrio e corporativo

# Cores base de texto e fundo (o CSS vai aprimorar isso)
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"